"use client";

import React from "react";
import Paper from "@mui/material/Paper";
import { DataGrid } from "@mui/x-data-grid";
import { Box, Table } from "@mui/material";
import Recruitment_Drawer from "./Recruitment_Drawer";
const columns = [
  { field: "sno", headerName: "S.No", width: 80 },
  { field: "date", headerName: "Date", width: 120 },
  { field: "name", headerName: "Name", width: 150 },
  { field: "phone", headerName: "Phone Number", width: 150 },
  { field: "location", headerName: "Location", width: 150 },
  {
    field: "qualification",
    headerName: "Qualification / Academics",
    width: 200,
  },
  { field: "certification", headerName: "Certification", width: 150 },
  { field: "experience", headerName: "Experience", width: 150 },
  { field: "reason", headerName: "Reason of Change", width: 180 },
  { field: "currentCTC", headerName: "Current CTC", width: 120 },
  { field: "expectedCTC", headerName: "Expected CTC", width: 120 },
  { field: "notice", headerName: "Notice Period", width: 120 },
  { field: "interviewDate", headerName: "Interview Date", width: 150 },
  { field: "time", headerName: "Time", width: 120 },
  { field: "panel", headerName: "Panel", width: 120 },
  { field: "mode", headerName: "Mode", width: 120 },
  { field: "status", headerName: "Status", width: 120 },
  { field: "source", headerName: "Source", width: 150 },
  { field: "refBy", headerName: "Ref By", width: 150 },
  { field: "comments", headerName: "Comments", width: 200 },
];

const sampleData = [
  {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
   {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },

     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },
     {
    id: 1,
    sno: 1,
    date: "2025-05-28",
    name: "John Doe",
    phone: "9876543210",
    location: "Mumbai",
    qualification: "B.Tech in CS",
    certification: "AWS Certified",
    experience: "5 years",
    reason: "Better opportunity",
    currentCTC: "10 LPA",
    expectedCTC: "15 LPA",
    notice: "30 days",
    interviewDate: "2025-06-05",
    time: "10:00 AM",
    panel: "Panel A",
    mode: "Online",
    status: "Scheduled",
    source: "LinkedIn",
    refBy: "Jane Smith",
    comments: "Highly recommended",
  },


];

export default function Recruitment() {
  return (
    <>
    <Recruitment_Drawer/>
    <Box sx={{ height: '80vh', width: '44%' }}>
      <DataGrid
        rows={sampleData}
        columns={columns}
        sx={{ border: 0 }}
        disableRowSelectionOnClick
        pageSizeOptions={[5, 10, 20]}
      />
    </Box>
    </>
  );
}
